routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/rek/{url}/{tel}/{own}/{ch}/{pl}/', function($url = false, $tel = false, $own = false, $ch = false, $pl = false){
    $rek = [
        'url' => explode('_', $url)[1],
        'tel' => explode('_', $tel)[1],
        'own' => explode('_', $own)[1],
        'ch' => explode('_', $ch)[1],
        'pl' => explode('_', $pl)[1],
    ];
    session(['rek' => $rek]);
    return redirect()->route('home');
});
Auth::routes();
Route::post('/users/parents/store', [App\Http\Controllers\UserController::class, 'store_parent'])->name('parents.store');
Route::post('/sms/{number}', [App\Http\Controllers\MangoController::class, 'sms']);
Route::post('/call/{number}', [App\Http\Controllers\MangoController::class, 'call']);
Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

Route::post('ckeditor/upload', [App\Http\Controllers\CKEditorController::class, 'upload'])->name('ckeditor.image-upload');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/mango', [App\Http\Controllers\HomeController::class, 'mango'])->name('mango');

Route::group([
    'prefix' => 'trainer',
    'middleware' => 'auth',
    'as' => 'trainer.'
], function(){
    Route::get('/', [App\Http\Controllers\Trainer\IndexController::class, 'show'])->name('trainer.show');
    Route::get('/{id}/edit', [App\Http\Controllers\Trainer\TrainersController::class, 'edit'])->name('trainer.edit');
    Route::post('/update', [App\Http\Controllers\Trainer\TrainersController::class, 'update'])->name('trainer.update');

    Route::get('/tasks', [App\Http\Controllers\Trainer\TaskController::class, 'index']);
    Route::get('/task/{id}', [App\Http\Controllers\Trainer\TaskController::class, 'showTask']);

    Route::get('/trainings', [App\Http\Controllers\Trainer\TrainingController::class, 'index']);
    Route::get('/trainings/{training}', [App\Http\Controllers\Trainer\TrainingController::class, 'show'])->name('trainings.show');
    Route::put('/trainings/{training}', [App\Http\Controllers\Trainer\TrainingController::class, 'update'])->name('trainings.update');
    Route::post('/trainings/{training}/accept', [App\Http\Controllers\Trainer\TrainingController::class, 'accept'])->name('trainings.accept');
    Route::post('/trainings/{training}/cancel', [App\Http\Controllers\Trainer\TrainingController::class, 'cancel'])->name('trainings.cancel');
});

Route::group([
    'prefix' => 'manager',
    'middleware' => 'auth',
    'as' => 'manager.'
], function(){

    Route::get('/', [App\Http\Controllers\Manager\IndexController::class, 'edit_profile'])->name('edit_profile');

    Route::get('/edit-profile', [App\Http\Controllers\Manager\IndexController::class, 'edit_profile']);
    Route::post('/update-profile', [App\Http\Controllers\Manager\IndexController::class, 'update_profile']);

    Route::resources([
        '/areas' => App\Http\Controllers\Manager\AreaController::class
    ]);

    Route::get('/trainers/create-task/{trainer_id}', [App\Http\Controllers\Manager\TrainertaskController::class, 'createTasks'])->name('createTasks');
    Route::get('/trainers/tasks/edit/{id}', [App\Http\Controllers\Manager\TaskController::class, 'editTask'])->name('showTask');
    Route::get('/trainers/tasks/{trainer_id}', [App\Http\Controllers\Manager\TrainertaskController::class, 'index']);
    Route::post('/trainers/task-store', [App\Http\Controllers\Manager\TrainertaskController::class, 'task_store']);

    Route::get('/tasks', [App\Http\Controllers\Manager\TaskController::class, 'index']);
    Route::get('/tasks/{date}', [App\Http\Controllers\Manager\TaskController::class, 'showTasksByDate'])->name('showMyTask');
    Route::get('/task/{id}', [App\Http\Controllers\Manager\TaskController::class, 'showTask']);
    Route::get('/task/edit/{id}', [App\Http\Controllers\Manager\TaskController::class, 'editTask']);
    Route::post('/task/store', [App\Http\Controllers\Manager\TaskController::class, 'storeTask']);
    Route::post('/task/update', [App\Http\Controllers\Manager\TaskController::class, 'updateTask']);
    Route::post('/tasks/filter/all_filter_club', [App\Http\Controllers\Manager\TaskController::class, 'filter_club']);
    Route::post('/tasks/filter/tag', [App\Http\Controllers\Manager\TaskController::class, 'filter_tag']);
    Route::post('/tasks/filter-date-range', [App\Http\Controllers\Manager\TaskController::class, 'filter_date_range']);
    Route::post('/tasks/filter/when', [App\Http\Controllers\Manager\TaskController::class, 'filter_when']);

    Route::get('/trainer/tasks', [App\Http\Controllers\Manager\TrainertaskController::class, 'index']);
    Route::get('/trainer/tasks/{date}', [App\Http\Controllers\Manager\TrainertaskController::class, 'showTasksByDate'])->name('showTrainerTask');
    Route::get('/trainer/task/{id}', [App\Http\Controllers\Manager\TrainertaskController::class, 'showTask']);
    Route::get('/trainer/task/edit/{id}', [App\Http\Controllers\Manager\TrainertaskController::class, 'editTask']);
    Route::post('/trainer/task/store', [App\Http\Controllers\Manager\TrainertaskController::class, 'storeTask']);
    Route::post('/trainer/task/update', [App\Http\Controllers\Manager\TrainertaskController::class, 'updateTask']);
    Route::post('/tasks/trainer/filter-date-range', [App\Http\Controllers\Manager\TaskController::class, 'trainer_filter_date_range']);
    Route::post('/tasks/trainer/club', [App\Http\Controllers\Manager\TaskController::class, 'trainer_filter_club']);
    Route::post('/tasks/trainer/tag', [App\Http\Controllers\Manager\TaskController::class, 'trainer_filter_tag']);
    Route::post('/tasks/trainer/filter-when', [App\Http\Controllers\Manager\TaskController::class, 'trainer_filter_when']);

    Route::get('/warehouses/create/{club_id}', [App\Http\Controllers\Manager\WarehouseController::class, 'create']);
    Route::post('/warehouses/store', [App\Http\Controllers\Manager\WarehouseController::class, 'store']);
    Route::get('/warehouses/edit/{warehouse_id}', [App\Http\Controllers\Manager\WarehouseController::class, 'edit']);
    Route::post('/warehouses/update', [App\Http\Controllers\Manager\WarehouseController::class, 'update']);
    Route::post('/warehouses/delete', [App\Http\Controllers\Manager\WarehouseController::class, 'delete']);
    Route::post('/warehouses/import', [App\Http\Controllers\Manager\WarehouseController::class, 'import']);

    Route::get('/crm/zayavki', [App\Http\Controllers\Manager\CRMController::class, 'index']);
    Route::get('/crm/create-client/{lead_id}', [App\Http\Controllers\Manager\ClientController::class, 'create_client']);
    Route::get('/trainings/{training}/checkUsers', [App\Http\Controllers\Manager\TrainingController::class, 'checkUsers'])->name('trainings.checkUsers');
    Route::get('/trainings/getData', [App\Http\Controllers\Manager\TrainingController::class, 'getData']);
    Route::delete('/trainings/destoryMany', [App\Http\Controllers\Manager\TrainingController::class, 'destoryMany'])->name('trainings.destroyMany');
    Route::post('/crm/leads/{lead}/temp_users', [App\Http\Controllers\Manager\LeadController::class, 'temp_users'])->name('temp_users.store');
    Route::get('/groups/{group}/trainings', [App\Http\Controllers\Manager\GroupsController::class, 'trainings']);
    Route::resources([
        '/crm/clients' => App\Http\Controllers\Manager\ClientController::class,
        '/clubs' => App\Http\Controllers\Manager\ClubController::class,
        'aboniments' => App\Http\Controllers\Manager\AbonimentController::class,
        'groups' => App\Http\Controllers\Manager\GroupsController::class,
        'trainers' => App\Http\Controllers\Manager\TrainersController::class,
        'workouts' => App\Http\Controllers\Manager\WorkoutsController::class,
        '/crm/leads' => App\Http\Controllers\Manager\LeadController::class,
        '/crm/clients' => App\Http\Controllers\Manager\ClientController::class,
        '/crm/children' => App\Http\Controllers\Manager\ChildrenController::class,
        'trainings' => App\Http\Controllers\Manager\TrainingController::class,
    ]);

    Route::post('/crm/clients/create-from-lead', [App\Http\Controllers\Manager\ClientController::class, 'create_from_lead']);


    Route::post('/crm/leads/lead_comment/store', [App\Http\Controllers\Manager\LeadController::class, 'lead_comment_create'])->name('lead_comment.store');
    Route::get('/crm/leads/client-create/{lead_id}', [App\Http\Controllers\Manager\ClientController::class, 'client_create']);
    Route::get('/crm/leads/client-delete/{lead_id}', [App\Http\Controllers\Manager\ClientController::class, 'client_delete']);
    Route::post('/crm/leads/filter/status', [App\Http\Controllers\Manager\ClientController::class, 'status_filter']);
    Route::post('/crm/leads/filter/start-date', [App\Http\Controllers\Manager\ClientController::class, 'start_date']);
    Route::post('/crm/leads/filter/entry-point', [App\Http\Controllers\Manager\ClientController::class, 'entry_point']);
    Route::post('/crm/leads/filter/channel', [App\Http\Controllers\Manager\ClientController::class, 'channel']);
    Route::post('/crm/leads/filter/manager', [App\Http\Controllers\Manager\ClientController::class, 'manager']);
    Route::post('/crm/leads/filter/club', [App\Http\Controllers\Manager\ClientController::class, 'clubs_filter']);
    Route::get('/crm/leads/filter/my', [App\Http\Controllers\Manager\ClientController::class, 'my_filter']);
    Route::post('/crm/leads/filter/when', [App\Http\Controllers\Manager\ClientController::class, 'when_filter']);
    Route::post('/crm/leads/filter/date-range', [App\Http\Controllers\Manager\ClientController::class, 'date_range']);
    Route::post('/crm/leads/filter/tasks-date', [App\Http\Controllers\Manager\ClientController::class, 'tasks_date']);

    Route::post('/crm/client/filter/type', [App\Http\Controllers\Manager\ClientController::class, 'type']);

app/Http/Controllers/Admin/TrainersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AbonimentGroup;
use App\Models\AdminTask;
use App\Models\Area;
use App\Models\AvailableDay;
use App\Models\AvailableDayTrainer;
use App\Models\Club;
use App\Models\ClubTrainer;
use App\Models\Group;
use App\Models\Level;
use App\Models\Spec;
use App\Models\TaskStatus;
use App\Models\TaskTag;
use App\Models\TrainerTask;
use App\Models\User;
use App\Models\Trainer;
use App\Models\UserRole;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class TrainersController extends BaseController
{
    public function index()
    {
        $trainers = Trainer::get();
        return view('admin/trainers/index', compact('trainers'));
    }

    public function show($group_id)
    {
        $trainer = Trainer::find($group_id);
        return view('admin/trainers/show', compact('trainer'));
    }

    public function create()
    {
        $available_days = AvailableDay::get();
        return view('admin/trainers/create', compact('available_days'));
    }

    public function edit($trainer_id)
    {
        $trainer = Trainer::find($trainer_id);
        $available_days = AvailableDay::whereNotIn('id', $trainer->availableDay->pluck('id'))->get();
        $statuses = TaskStatus::get();
        $tasks = TrainerTask::where('trainer_id', $trainer_id)->get();
        $tasktags  = TaskTag::get();
        return view('admin/trainers/edit', compact(
            'trainer', 'available_days',
            'statuses', 'tasks', 'tasktags'
        ));
    }

    public function store(Request $request)
    {
         $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $data = $request->all();

        $trainer = new Trainer();
        $users = new User();

        $user = User::find($users->id);
        $trainer->name = $data['name'];
        $trainer->surname = $data['surname'];
        $trainer->patronymic = $data['patronymic'];
        $trainer->birthday = $data['birthday'];
        $trainer->phone = $data['phone'];
        $trainer->vk = $data['address'];
        $trainer->instagram = $data['instagram'];
        $trainer->education = $data['education'];
        $trainer->license = $data['license'];
        $trainer->experience = $data['experience'];
        $trainer->family_status = $data['family_status'];
        $trainer->children = $data['children'];
        $trainer->career = $data['career'];
        $trainer->password = Hash::make($data['password']);
        $trainer->password_confirmation = Hash::make($data['password_confirmation']);
          if ($request->password != $request->password_confirmation)
        {
            return back()->withErrors(['Пароли не совпадают']);
        }
        $trainer->user_id = 1;

        if ($request->hasFile('image')){
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension(); // you can also use file name
            $fileName = time().'.'.$extension;
            $path = public_path().'/trainer/avatarss';
            $uplaod = $file->move($path,$fileName);
            $trainer->image = $fileName;
        } else {
            $trainer->image = "avatar.png";
        }

        $trainer->save();


    }


    public function update(Request $request)
    {

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'password' => ['nullable', 'string', 'min:8', 'confirmed']
        ]);

        $data = $request->all();


        $trainer = Trainer::find($request->trainer_id);
        $user = User::find($trainer->user_id);
        $trainer->fill($data);
        if ($request->hasFile('image')){
            \File::delete("/trainer/avatars/$trainer->image");
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension(); // you can also use file name
            $fileName = time().'.'.$extension;
            $path = public_path().'/trainer/avatars';
            $uplaod = $file->move($path,$fileName);
            $trainer->image = $fileName;
        }

        $chars = ['+',' ', '(', ')', '-'];
        $numb = str_replace($chars, '', $data['phone']);
        $trainer->user_id = $user->id;
        $trainer->name = $data['name'];
        $trainer->surname = $data['surname'];
        $trainer->patronymic = $data['patronymic'];
        $user->email = $data['email'];
        $trainer->gender = $data['gender'];
        $trainer->birthday = \Carbon\Carbon::parse($data['birthday']);
        $trainer->phone = $numb;
        $trainer->vk = $data['address'];
        $trainer->instagram = $data['instagram'];
        $trainer->education = $data['education'];
        $trainer->license = $data['license'];
        $trainer->experience = $data['experience'];
        $trainer->family_status = $data['family_status'];
        $trainer->children = $data['children'];
        $trainer->career = $data['career'];

        if($data['password'] != null)
        {
            $user->password = Hash::make($data['password']);
        }
        $user->update();
        $trainer->update();
        return redirect('admin/trainers/'.$trainer->id.'/edit');

    }


    public function destroy(Trainer $trainer)
    {
        $ab_group = ClubTrainer::where('trainer_id', $trainer->id)->get();
        if (count($ab_group) > 0)
        {
            return back()->withErrors(['Тренер добавлен в клуб. Сначала удалите его из клуба']);
        }
        $user = User::find($trainer->user_id);
        $trainer->delete();
        $user->delete();
        return redirect('/admin/trainers');
    }

    public function deleteTrainer($trainer_id)
    {
        $club_trainers = ClubTrainer::where('trainer_id', $trainer_id)->get();
        if (count($club_trainers) > 0)
        {
            foreach ($club_trainers as $club_trainer)
            {
                $club_trainer->delete();
            }
        }
        $trainer = Trainer::find($trainer_id);
        $user = User::find($trainer->user_id);

        $user_role = UserRole::where('user_id', $user->id)->first();
        $user_role->delete();

        $trainer->delete();
        $user->delete();

        return redirect('/admin/trainers')->with('success', 'Тренер удален');
    }
}

app/Http/Controllers/Trainer/BaseController.php
<?php

namespace App\Http\Controllers\Trainer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BaseController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            if (!Auth::user()->hasRole('Тренер')) {
                abort(403, 'Unauthorized action.');
            }
            return $next($request);
        });
    }
}

app/Http/Controllers/Trainer/TaskController.php
<?php

namespace App\Http\Controllers\Trainer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    //
}

resources/views/trainers/trainings/index.blade.php
@extends('trainers.layouts.app')

@section('content')
<div id="page_content_inner">
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped uk-table-hover">
                    <thead>
                    <tr>
                        <th>Дата / Время</th>
                        <th>Группа</th>
                        <th>Обучаемых</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($trainings as $item)
                            <tr>
                                <td>{{ $item->date }} {{ $item->start }}-{{ $item->end }}</td>
                                <td>{{$item->group->age_start}} - {{$item->group->age_end}}</td>
                                <td>{{$item->children->count()}}</td>
                                <td class="uk-text-center">
                                    @if($item->accept == 0)
                                    <form style="display: inline" action="{{route('trainer.trainings.accept', $item->id)}}" method="post">
                                        @csrf
                                        <button class="uk-button-link"><i class="md-icon material-icons">check</i></button>
                                    </form>
                                    <a style="display: inline-block" onclick="$('#cancel-form').attr('action', '/trainer/trainings/{{$item->id}}/cancel')" class="uk-button-link" data-uk-modal="{target:'#cancel'}"><i class="md-icon material-icons">close</i></a>
                                    @elseif($item->accept == 1)
                                    <a style="display: inline-block" href="{{route('trainer.trainings.show', $item->id)}}" class="uk-button-link">к тренировке</a>
                                    @else
                                    {{$item->report}}
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="uk-modal" id="cancel">
    <div class="uk-modal-dialog">
        <form action="" id="cancel-form" method="post">
            @csrf
            <div class="uk-modal-header">
                <h3 class="uk-modal-title">Укажите причину отказа</h3>
            </div>
            <textarea required name="report" rows="3" class="md-input"></textarea>
            <div class="uk-modal-footer uk-text-right">
                <button type="button" class="md-btn md-btn-flat uk-modal-close">Отмена</button>
                <button class="md-btn md-btn-flat md-btn-flat-primary">Отказаться</button>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/trainers/trainings/show.blade.php
@extends('trainers.layouts.app')

@section('content')

<div id="page_content_inner">
    <div class="md-card">
        <div class="md-card-content">
            <h3 class="heading_c uk-margin-medium-bottom">Настройки тренировки <br><b>{{$training->date}}</b></h3>
            <form action="{{route('trainer.trainings.update', $training->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="uk-form-row">
                    <label>Отчет тренера</label>
                    <textarea rows="3" name="report" class="md-input">{{$training->report}}</textarea>
                </div>
                <div class="uk-form-row">
                    <div class="uk-form-file md-btn md-btn-block md-btn-small md-btn-primary">
                        Прикрепить видео тренировки
                        <input name="video" type="file">
                    </div>
                    @if($training->video)
                    <video src="/storage/{{$training->video}}" controls="true"></video>
                    @endif
                </div>
                <div class="uk-form-row">
                    <div class="uk-form-file md-btn md-btn-block md-btn-small md-btn-primary">
                        Прикрепить конспект
                        <input name="conspect" type="file">
                    </div>
                    @if($training->conspect)
                    <a href="/storage/{{$training->video}}" target="_blank">посмотреть</a>
                    @endif
                </div>
                <div class="uk-form-row">
                    <button class="md-btn md-btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>

@stop